### ISSUE TITLE
master branch - origin_sites not defined in JSON caster map

### ISSUE THREAD

**Issue by luceos** [virtuozzo/OnApp-PHP-Wrapper-External#13]
Working with the latest master branch; I came across the following error when trying to load a CDN resource:

```
exception 'ErrorException' with message 'Undefined index: origin_sites' in /domains/<website>/lib/onapp/OnApp-PHP-Wrapper-External/Helper/Caster/JSON.php:128
Stack trace:
#0 /domains/<website>/lib/onapp/OnApp-PHP-Wrapper-External/Helper/Caster/JSON.php(128): error_handler(8, 'Undefined index...', '<domain>....', 128, Array)
#1 /domains/<website>/lib/onapp/OnApp-PHP-Wrapper-External/Helper/Caster/JSON.php(100): OnApp_Helper_Caster_JSON->process(Object(stdClass))
#2 /domains/<website>/lib/onapp/OnApp-PHP-Wrapper-External/Helper/Caster.php(51): OnApp_Helper_Caster_JSON->unserialize('OnApp_CDNResour...', '{"cdn_resource"...', Array, 'cdn_resource')
#3 /domains/<website>/lib/onapp/OnApp-PHP-Wrapper-External/OnApp.php(1154): OnApp_Helper_Caster->unserialize('OnApp_CDNResour...', '{"cdn_resource"...', Array, 'cdn_resource')
#4 /domains/<website>/lib/onapp/OnApp-PHP-Wrapper-External/OnApp.php(1249): OnApp->castStringToClass(Array)
#5 /domains/<website>/lib/onapp/onapp_client.php(75): OnApp->load('14')
#6 /domains/<website>/lib/forms/cdn.form.php(30): OnApp_client::getCDNResource('14')
```

**Comment by luceos** [comment]
So it seems our 3.0.8 uses fields that are currently implemented for 3.1 API only; it concerns the following:

```

                                $this->fields[ 'cname' ] = array(
                                        ONAPP_FIELD_MAP  => 'cname',
                                        ONAPP_FIELD_TYPE => 'string',
                                );
                                $this->fields[ 'push_origin_hostname' ] = array(
                                        ONAPP_FIELD_MAP  => 'push_origin_hostname',
                                        ONAPP_FIELD_TYPE => 'string',
                                );
```

Additionally there must be some error in the naming of the origin_sites, as it's not used in any of the API's:

```

                $this->fields[ 'origin_sites' ]                            = array(
                    ONAPP_FIELD_MAP => '_origins',
                    ONAPP_FIELD_TYPE => 'array',
                    ONAPP_FIELD_CLASS => 'CDNResource_Origin',
                );

```

As edited in CDNResource.php on line 211 and after.

**Comment by luceos** [comment]
No idea how to load the origin sites aka origins now though..

**Comment by ghost** [comment]
What happens when you do not convert notices to exceptions?

**Comment by ghost** [comment]
@Luceos couldn't you give us more details how to reproduce?

**Comment by luceos** [comment]
Sorry, didn't see your responses.. 

Reproduction is quite easy, we use OnAPP 3.0.8 with the current master branch (at opening of issue). We simply load a CDN resource with the following intermediairy class, where we use `getCDNResource` to get one CDN resource. For all other calls this works.

Obviously the issue is that our OnAPP returns more information than the wrapper expects to return. As such origin_sites is something that will or is renamed in 3.1 to origins?

```
require_once('OnApp-PHP-Wrapper-External/OnAppInit.php');
require_once('OnApp-PHP-Wrapper-External/OnApp.php');

class OnApp_client {
    private static $c   = null;
    private function __construct() {
        $this -> host   = <onapp hostname>
        $this -> un = <onapp admin email address>;
        $this -> pw = <onapp credential>;
        return true;
    }
    static public function get_instance() {
        if( is_null( self::$c )) {
            self::$c    = new OnApp_client();
        }
        return self::$c;
    }
    static public function getUser( $id ) {
        $c = self::get_instance();
        $u = new OnApp_User;
        $u -> auth( $c -> host , $c -> un , $c -> pw );
        return $u -> load( $id );
    }
    static public function getProfile( $id ) {
        $c = self::get_instance();
        $u = new OnApp_Profile;
        $u -> auth( $c -> host , $c -> un , $c -> pw );
        return $u -> load( $id );
    }
    static public function getVM( $id ) {
        $c = self::get_instance();
        $u = new OnApp_VirtualMachine;
        $u -> auth( $c -> host , $c -> un , $c -> pw );
        return $u -> load( $id );
    }
    static public function getVMs( $id=NULL ) {
        $c = self::get_instance();
        $u = new OnApp_VirtualMachine;
        $u -> auth( $c -> host , $c -> un , $c -> pw );
        return $u -> getList( $id );
    }
    static public function getVMNetworkInterfaces( $id ) {
        $c = self::get_instance();
        $u = new OnApp_VirtualMachine_NetworkInterface;
        $u -> auth( $c -> host , $c -> un , $c -> pw );
        if(!$u->isAuthenticate()) {
            printf("Could not log in to the OnApp Control Panel server\n");
            printf($u->getErrorsAsString("\n"));
            exit(1);
        }
        return $u -> getList( $id );
    }
    static public function getVMNetworkUsage( $id=false , $interface=null ) {
        if( $id ) {
            $c = self::get_instance();
            $u = new ONAPP_VirtualMachine_NetworkInterface_Usage;
            $u -> auth( $c -> host , $c -> un , $c -> pw );

            return $u -> getList( $id , $interface );
        }
        return false;
    }
    static public function getCDNResources() {
        $c = self::get_instance();
        $cdn = new OnApp_CDNResource;
        $cdn -> auth( $c -> host , $c -> un , $c -> pw );
        return $cdn -> getList();
    }
    static public function getCDNResource($id) {
        $c = self::get_instance();
        $cdn = new OnApp_CDNResource;
        $cdn -> auth( $c -> host , $c -> un , $c -> pw );
        return $cdn -> load( $id );
    }
    static public function getCDNUsage($id, $startdate) {
        $c = self::get_instance();
        $cdn = new OnApp_CDNResource_BillingStatistic;
        $cdn -> auth( $c -> host , $c -> un , $c -> pw );
        return $cdn -> getList( $id, array('period[startdate]' => AnewtDateTime::sql_date($startdate)) );
    }
}
```
